### ISSUE TITLE
Скласти інтро

### ISSUE THREAD

**Issue by Natali2012** [Natali2012/homepage#4]
Скласти інтро (вступ), де в 2-4 реченнях описати, що замовник робить, що подобається робити, що хочеться робити краще, що важливо робити, тощо.

**Comment by Dima0308** [comment]
I am the brightest personality of this century. I always go towards my goal. I learn something new every day. I'm getting better every day

**Comment by Natali2012** [comment]
Thanks))))

**Comment by Natali2012** [comment]
<h2>Resume</h2>
<p>&mdash; I am the brightest personality of this century. I always go towards my goal. I learn something new every day. I'm getting better every day</p>
