### ISSUE TITLE
Скласти інтро

### ISSUE THREAD

**Issue by Natali2012** [Natali2012/homepage#4]
Скласти інтро (вступ), де в 2-4 реченнях описати, що замовник робить, що подобається робити, що хочеться робити краще, що важливо робити, тощо.

**Comment by Dima0308** [comment]
The customer is a very important person. He likes when all the work is done on time. I really want to develop and become better and better every day. And of course to achieve your main goal.

**Comment by Natali2012** [comment]
Thanks you for the help))))
