### ISSUE TITLE
Скласти блок контактної інформації

### ISSUE THREAD

**Issue by Natali2012** [Natali2012/homepage#5]
Посилання на соцмережі (Facebook чи Instagram, тощо), номер телефону чи адреса електронної скриньки, тощо. Може не всі лінки в світі, а тільки ті, що дійсно доречні.

**Comment by Dima0308** [comment]
**Mark Elliot Zuckerberg**
- https://www.facebook.com/zuck
- https://www.forbes.com/profile/mark-zuckerberg/#238b9d0c3e06
- http://www.businessinsider.com/mark-zuckerbergs-hacker-for-hire-profile-from-2002-2010-7
- https://wikidata-externalid-url.toolforge.org/?p=345&url_prefix=https://www.imdb.com/&id=nm3212916

**Comment by Natali2012** [comment]
Дуже дякую)))))
