### ISSUE TITLE
Скласти блок контактної інформації

### ISSUE THREAD

**Issue by Natali2012** [Natali2012/homepage#5]
Посилання на соцмережі (Facebook чи Instagram, тощо), номер телефону чи адреса електронної скриньки, тощо. Може не всі лінки в світі, а тільки ті, що дійсно доречні.

**Comment by Dima0308** [comment]
1. https://www.facebook.com/zuck
2. https://twitter.com/tsukerbergm
3. https://www.forbes.com/billionaires/

**Comment by Natali2012** [comment]
Дякую))))

**Comment by Natali2012** [comment]
<h1 class="name">Mark Zuckerberg</h1>
<div class="job">Facebook creator</div>
<ul class="contacts">
 <li>
      <a href="https://twitter.com/tsukerbergm" rel="author" class"twitter">     
           <svg xmlns="http://www.w3.org/2000/svg"  viewBox="0 0 48 48" width="96px" height="96px"><linearGradient id="_osn9zIN2f6RhTsY8WhY4a" x1="10.341" x2="40.798" y1="8.312" y2="38.769" gradientUnits="userSpaceOnUse"><stop offset="0" stop-color="#2aa4f4"/><stop offset="1" stop-color="#007ad9"/></linearGradient><path fill="url(#_osn9zIN2f6RhTsY8WhY4a)" d="M46.105,11.02c-1.551,0.687-3.219,1.145-4.979,1.362c1.789-1.062,3.166-2.756,3.812-4.758	c-1.674,0.981-3.529,1.702-5.502,2.082C37.86,8.036,35.612,7,33.122,7c-4.783,0-8.661,3.843-8.661,8.582	c0,0.671,0.079,1.324,0.226,1.958c-7.196-0.361-13.579-3.782-17.849-8.974c-0.75,1.269-1.172,2.754-1.172,4.322	c0,2.979,1.525,5.602,3.851,7.147c-1.42-0.043-2.756-0.438-3.926-1.072c0,0.026,0,0.064,0,0.101c0,4.163,2.986,7.63,6.944,8.419	c-0.723,0.198-1.488,0.308-2.276,0.308c-0.559,0-1.104-0.063-1.632-0.158c1.102,3.402,4.299,5.889,8.087,5.963	c-2.964,2.298-6.697,3.674-10.756,3.674c-0.701,0-1.387-0.04-2.065-0.122C7.73,39.577,12.283,41,17.171,41	c15.927,0,24.641-13.079,24.641-24.426c0-0.372-0.012-0.742-0.029-1.108C43.483,14.265,44.948,12.751,46.105,11.02"/></svg>
     <span>Mark Zuckerberg</span>
   </a>
</li>
 <li>
      <a href="https://www.facebook.com/zuck" rel="author" class"faceebook">
     <svg xmlns="http://www.w3.org/2000/svg"  viewBox="0 0 100 100" width="100px" height="100px"><path fill="#ee3e54" d="M13 27A2 2 0 1 0 13 31A2 2 0 1 0 13 27Z"/><path fill="#f1bc19" d="M77 12A1 1 0 1 0 77 14A1 1 0 1 0 77 12Z"/><path fill="#fce0a2" d="M50 13A37 37 0 1 0 50 87A37 37 0 1 0 50 13Z"/><path fill="#f1bc19" d="M83 11A4 4 0 1 0 83 19A4 4 0 1 0 83 11Z"/><path fill="#ee3e54" d="M87 22A2 2 0 1 0 87 26A2 2 0 1 0 87 22Z"/><path fill="#fbcd59" d="M81 74A2 2 0 1 0 81 78 2 2 0 1 0 81 74zM15 59A4 4 0 1 0 15 67 4 4 0 1 0 15 59z"/><path fill="#ee3e54" d="M25 85A2 2 0 1 0 25 89A2 2 0 1 0 25 85Z"/><path fill="#fff" d="M18.5 51A2.5 2.5 0 1 0 18.5 56A2.5 2.5 0 1 0 18.5 51Z"/><path fill="#f1bc19" d="M21 66A1 1 0 1 0 21 68A1 1 0 1 0 21 66Z"/><path fill="#fff" d="M80 33A1 1 0 1 0 80 35A1 1 0 1 0 80 33Z"/><path fill="#4985c1" d="M35,72.3c-4,0-7.3-3.3-7.3-7.3V35c0-4,3.3-7.3,7.3-7.3h30c4,0,7.3,3.3,7.3,7.3v30c0,4-3.3,7.3-7.3,7.3H35z"/><path fill="#472b29" d="M65,28.4c3.6,0,6.6,3,6.6,6.6v30c0,3.6-3,6.6-6.6,6.6H35c-3.6,0-6.6-3-6.6-6.6V35c0-3.6,3-6.6,6.6-6.6H65 M65,27H35c-4.4,0-8,3.6-8,8v30c0,4.4,3.6,8,8,8h30c4.4,0,8-3.6,8-8V35C73,30.6,69.4,27,65,27L65,27z"/><path fill="#fdfcee" d="M68.5,47.9v1.8V64c0,2.5-2,4.5-4.5,4.5H36c-2.5,0-4.5-2-4.5-4.5V36c0-2.5,2-4.5,4.5-4.5h25.4H64 c2.5,0,4.5,2,4.5,4.5v3.4v2v1v1.1v2.9V47.9"/><path fill="#472b29" d="M68.5 47.4c-.3 0-.5-.2-.5-.5V43c0-.3.2-.5.5-.5S69 42.7 69 43v3.9C69 47.2 68.8 47.4 68.5 47.4zM68.5 40.5c-.3 0-.5-.2-.5-.5v-2c0-.3.2-.5.5-.5S69 37.7 69 38v2C69 40.3 68.8 40.5 68.5 40.5z"/><path fill="#472b29" d="M64,69H36c-2.8,0-5-2.2-5-5V36c0-2.8,2.2-5,5-5h25.4c0.3,0,0.5,0.2,0.5,0.5S61.7,32,61.4,32H36 c-2.2,0-4,1.8-4,4v28c0,2.2,1.8,4,4,4h28c2.2,0,4-1.8,4-4V49.6c0-0.3,0.2-0.5,0.5-0.5s0.5,0.2,0.5,0.5V64C69,66.8,66.8,69,64,69z"/><path fill="#4985c1" d="M46.5,43.4c0,0.6,0,3.1,0,3.1h-2.1v3.6h2.1v11.4h5V50.1h2.9c0,0,0.3-1.7,0.4-3.6c-0.4,0-4.1,0-4.1,0 s0-2.2,0-2.6c0-0.4,0.5-0.9,1-0.9s2.2,0,3.3,0c0-0.6,0-2.5,0-4.3c-1.4,0-2.9,0-3.6,0C46.4,38.6,46.5,42.8,46.5,43.4z"/><path fill="#472b29" d="M51.5,62h-5c-0.3,0-0.5-0.2-0.5-0.5V50.6h-1.6c-0.3,0-0.5-0.2-0.5-0.5v-3.6c0-0.3,0.2-0.5,0.5-0.5H46v-2.6h0.5 l-0.5,0c0-1.6,0.5-2.9,1.4-3.8c0.9-1,2.3-1.4,4.1-1.4h3.6c0.3,0,0.5,0.2,0.5,0.5v4.3c0,0.3-0.2,0.5-0.5,0.5h-3.3 c-0.2,0-0.5,0.3-0.5,0.4V46h3.6c0.1,0,0.3,0.1,0.4,0.2c0.1,0.1,0.1,0.2,0.1,0.4c-0.1,1.9-0.4,3.5-0.4,3.6c0,0.2-0.2,0.4-0.5,0.4H52 v10.9C52,61.8,51.8,62,51.5,62z M47,61h4V50.1c0-0.3,0.2-0.5,0.5-0.5H54c0.1-0.5,0.2-1.5,0.3-2.6h-3.5c-0.3,0-0.5-0.2-0.5-0.5v-2.6 c0-0.7,0.8-1.4,1.5-1.4h2.8v-3.3h-3.1c-1.5,0-2.7,0.4-3.4,1.1C47.4,41,47,42,47,43.3c0,0,0,0,0,0v3.1c0,0.3-0.2,0.5-0.5,0.5h-1.6 v2.6h1.6c0.3,0,0.5,0.2,0.5,0.5V61z"/></svg>
     <span>Mark Zuckerberg</span>
   </a>
</li>
<li>
      <a href="https://www.forbes.com/billionaires/" rel="author" class"forbs">
           <svg xmlns="http://www.w3.org/2000/svg"  viewBox="0 0 48 48" width="96px" height="96px"><linearGradient id="iCKXIOPdkM~UA8JX4zrana" x1="39.001" x2="41.528" y1="29.5" y2="29.5" gradientUnits="userSpaceOnUse"><stop offset="0" stop-color="#c48f0c"/><stop offset=".251" stop-color="#d19b16"/><stop offset=".619" stop-color="#dca51f"/><stop offset="1" stop-color="#e0a922"/></linearGradient><path fill="url(#iCKXIOPdkM~UA8JX4zrana)" d="M38.999,25H38v9h1.333c0.975,0,1.808-0.703,1.972-1.664l0.653-3.832	C42.269,26.672,40.857,25,38.999,25z"/><linearGradient id="iCKXIOPdkM~UA8JX4zranb" x1="-201" x2="-198.472" y1="29.5" y2="29.5" gradientTransform="matrix(-1 0 0 1 -192 0)" gradientUnits="userSpaceOnUse"><stop offset="0" stop-color="#c48f0c"/><stop offset=".251" stop-color="#d19b16"/><stop offset=".619" stop-color="#dca51f"/><stop offset="1" stop-color="#e0a922"/></linearGradient><path fill="url(#iCKXIOPdkM~UA8JX4zranb)" d="M9.001,25H10v9H8.667c-0.975,0-1.808-0.703-1.972-1.664l-0.653-3.832	C5.731,26.672,7.143,25,9.001,25z"/><radialGradient id="iCKXIOPdkM~UA8JX4zranc" cx="24" cy="25.5" r="17.396" gradientUnits="userSpaceOnUse"><stop offset="0" stop-color="#ffcf54"/><stop offset=".261" stop-color="#fdcb4d"/><stop offset=".639" stop-color="#f7c13a"/><stop offset="1" stop-color="#f0b421"/></radialGradient><path fill="url(#iCKXIOPdkM~UA8JX4zranc)" d="M24,6C16.598,6,9,9,9,25c0,1.281,0,5.92,0,7.288C9,38,18,45,24,45s15-7,15-12.712	c0-1.368,0-6.007,0-7.288C39,9,31.402,6,24,6z"/><radialGradient id="iCKXIOPdkM~UA8JX4zrand" cx="9.386" cy="5.933" r="42.765" gradientUnits="userSpaceOnUse"><stop offset="0" stop-color="#c26715"/><stop offset=".508" stop-color="#b85515"/><stop offset="1" stop-color="#ad3f16"/></radialGradient><path fill="url(#iCKXIOPdkM~UA8JX4zrand)" d="M24,4c-7.982,0-10,3-10,3c-3.245,0.479-7,4.566-7,10c0,3.032,0.653,4.439,2,12c1-12,2-16,4-16	c3,0,3,2,11.778,2C29.801,15,32,13,34,13c5,0,5,14.108,5,16c0.806-7.405,1-9.351,1-12C40,10.712,35.383,4,24,4z"/><radialGradient id="iCKXIOPdkM~UA8JX4zrane" cx="20.832" cy="9.178" r="53.981" gradientUnits="userSpaceOnUse"><stop offset="0" stop-color="#c26715"/><stop offset=".508" stop-color="#b85515"/><stop offset="1" stop-color="#ad3f16"/></radialGradient><path fill="url(#iCKXIOPdkM~UA8JX4zrane)" d="M24,3c-7.982,0-10,4-10,4c-0.08,2.125,1,4,1,4s1.46,3,9.778,3C29.801,14,37,11.003,37,3	C37,3,35.383,3,24,3z"/></svg>
     <span>Mark Zuckerberg</span>
   </a>
</li>
