### ISSUE TITLE
Скласти таймлайн

### ISSUE THREAD

**Issue by Natali2012** [Natali2012/homepage#6]
Скласти список всіх (важливих) життєвих подій, визначних дат, досягнень, періодів, що дали приємний і неприємний досвід, тощо. В цьому конкретному випадку довгих списків не буває, натомість бувають погано згорнуті, тому пакуємо сюди все підряд, а про "лишні" події можна буде промовчати пізніше. Список повинен бути систематизованим і посортованим в такий спосіб, щоб читач швидко зрозумів "паттерн" і міг легко орієнтуватись в просторі і часі цього резюме.

**Comment by Dima0308** [comment]
Mark Zuckenberg

1984
Mark Zuckenberg was born

2020
He went to Harvard University

2009
An agreement was signed according to which DST bought 1.96% of Facebook shares for $ 200 million.

2010
Time magazine named Zuckerberg Person of the Year

2014
Mark ranked 14th in the Forbes Top 15 with a net worth of $ 33.6 billion

2016
Met with Pope Francis

2018
Testified before the US Congress in connection with the Cambridge Analytica scandal

**Comment by Natali2012** [comment]
дякую-дякую))))
