### ISSUE TITLE
Скласти таймлайн

### ISSUE THREAD

**Issue by Natali2012** [Natali2012/homepage#6]
Скласти список всіх (важливих) життєвих подій, визначних дат, досягнень, періодів, що дали приємний і неприємний досвід, тощо. В цьому конкретному випадку довгих списків не буває, натомість бувають погано згорнуті, тому пакуємо сюди все підряд, а про "лишні" події можна буде промовчати пізніше. Список повинен бути систематизованим і посортованим в такий спосіб, щоб читач швидко зрозумів "паттерн" і міг легко орієнтуватись в просторі і часі цього резюме.

**Comment by Dima0308** [comment]
**_EXPERIENCE_**

1984
Mark was born  in White Plains

2009
An agreement was signed according to which DST bought 1.96% of Facebook shares for $ 200 million

2010
Time magazine named Zuckerberg Person of the Year

2012
Mark Zuckerberg married his longtime girlfriend Priscilla Chan.

2013
Zuckerberg is in the Top 10 Youngest Billionaires, according to Forbes he is ranked 2nd in the ranking

2014
Zuckerberg spent $ 100 million to buy plots of land on the north coast of Kauai


2016
Met with Pope Francis

**Comment by Natali2012** [comment]
Thank you)))))
