### ISSUE TITLE
Скласти додаткові інформаційні блоки

### ISSUE THREAD

**Issue by Natali2012** [Natali2012/homepage#7]
Можна зробити резюме менш формальним, додавши додаткові блоки, які містять корисну інформацію, але подають її в "розважальній" формі. Наприклад, що подобається і не подобається, сильні і слабкі сторони, перелік навиків чи хобі, інфографіка або ж інтерактивні модулі, тощо. Варто написати контент такого блоку раніше, ніж починати верстку, бо його розміри впливатимуть на розміщення елементів на сторінці.

**Comment by Dima0308** [comment]
During his school years, Mark was engaged in computer programming and developed a network version of the game "Risk". 
He pointed out his area of ​​interest as “C, C ++, Java, Visual Basic, VBscript, JavaScript, PHP and ASP” [9]. Zuckerberg has repeatedly characterized himself as a hacker by calling. Back in college, Microsoft employees drew attention to Mark after he wrote the Synapse program, which allowed the computer to independently compose a sequence of musical hits for its owner.  
Together with Chris Hughes and Dustin Moskowitz, he began to create the social network Facebook. On December 8, 2010, Mark Zuckerberg announced that he was joining The Giving Oath, a philanthropic campaign by billionaires Warren Buffett and Bill Gates.

**Comment by Natali2012** [comment]
Дуже дякую))))
