### ISSUE TITLE
Скласти додаткові інформаційні блоки

### ISSUE THREAD

**Issue by Natali2012** [Natali2012/homepage#7]
Можна зробити резюме менш формальним, додавши додаткові блоки, які містять корисну інформацію, але подають її в "розважальній" формі. Наприклад, що подобається і не подобається, сильні і слабкі сторони, перелік навиків чи хобі, інфографіка або ж інтерактивні модулі, тощо. Варто написати контент такого блоку раніше, ніж починати верстку, бо його розміри впливатимуть на розміщення елементів на сторінці.

**Comment by Dima0308** [comment]
**LANGUAGES**
English Русский

**SKILLS**
He specified his area of ​​interest as “C, C ++, Java, Visual Basic, VBscript, JavaScript, PHP and ASP” [8]. Zuckerberg has repeatedly characterized himself as a hacker by vocation. Back in college, Mark was noticed by Microsoft employees after he wrote the Synapse program, which allowed the computer to independently compose a sequence of musical hits for its owner.

**CHARACTER**
The versatility of human nature knows no boundaries. Who would have thought that the world's youngest billionaire and most tastelessly dressed male celebrity, resourceful programmer and prominent polyglot, the planet's most powerful Jew and up-and-coming swordsman are all characteristics of the same person.

**LIKES**
Based on the Facemash software, Mark Zuckerberg created a communication masterpiece in the form of the social network Facebook, which expanded the communication of Harvard students on the local network. In a matter of days, the project outgrew the boundaries of the Harvard campus, and Ivy League universities in Boston, New York, Massachusetts and Canada joined it. Stanford and Columbia University soon joined.

**`DISLIKES`**
Lawsuits are the flip side of wealth and popularity. And they have grown at Mark Zuckerberg and continue to grow by leaps and bounds. Together with them, all sorts of "titles and regalia" fell in his address. Below are just the most curious of them.

**Comment by Natali2012** [comment]
Дуже дякую любий друже))))))
